### ISSUE TITLE
It refuses to start 

### ISSUE THREAD

**Issue by Decards** [hyprutils/hyprgui#61]
Hi, I can't start Hyprgui.

I got it from AUR and tried both -bin and non -bin versions same results: 
If i click on the icon nothing happens. 

if i type "hyprgui" in terminal absolutly nothing happens it just hang indefinitely. i have to ctrl-c it.

i tried "sudo hyprgui"  for the science i get : 

Authorization required, but no authorization protocol specified
(hyprgui:900268): Gtk-WARNING **: 08:32:49.274: Failed to open display

so i did : " xhost si:localuser:root"

and  now "sudo hyprgui" starts ! but i need it to work in non sudo.

i also tried the versions on your release page same issue. i tried "xhost si:localuser:<myusername>" .  no changes.

**Comment by nnyyxxxx** [comment]
try:

``GDK_BACKEND=wayland hyprgui``

**Comment by nnyyxxxx** [comment]
this is most likely due to your env vars not being set properly

**Comment by Decards** [comment]
It solved it thanks, 
I've modified my hyprland.conf accordingly.

Thank you !
