### ISSUE TITLE
[Enhancement Request] - Tab width size

### ISSUE THREAD

**Issue by JaKooLit** [hyprutils/hyprgui#68]
First, Great job on the project!

This is not really an issue but more on enhancement

just a request if possible,

can you add a preferrence on the hyprgui itself, for a tab width size?

By default, it seems it is writing the configs with 4 spaces as default width size

if can add a preference like 2 or 6 or 8 or whichever user prefered. You can set 4 spaces of course since its the usual default 

thanks

**Comment by nnyyxxxx** [comment]
yeah, i'll implement this in a more dynamic way, ill just have it go off of the tabs of other modules inside of the parsed categories.

will be done by tomorrow.

**Comment by adamperkowski** [comment]
"i'll implement this"
proceeds to assign me

**Comment by nnyyxxxx** [comment]
https://github.com/hyprutils/hyprparser/pull/20

implemented here, will be included in the next release along with the fixes for the categories you mentioned on reddit.
