### ISSUE TITLE
[New Feature] Custom hyprland.conf path 

### ISSUE THREAD

**Issue by mrfluffy-dev** [hyprutils/hyprgui#78]
Firstly cool project.

Secondly I was wondering if the .conf path could be more flexible I was thinking the [official](https://wiki.hyprland.org/Configuring/Environment-variables/) env var `HYPRLAND_CONFIG` and if it doesn't exist fallback to `.config/hypr/hyprland.conf` .

best way I can think would be to do something like this.
```rust
fn get_config_path() -> PathBuf {
    // Check the environment variable `HYPRLAND_CONFIG`
    if let Ok(config_path) = env::var("HYPRLAND_CONFIG") {
        let path = PathBuf::from(config_path);
        if path.exists() {
            return path;
        }
    }
    // Fallback to the default configuration path
    dirs::home_dir().unwrap().join(".config/hypr/hyprland.conf")
}
```

instead of the hard coded `const CONFIG_PATH: &str = ".config/hypr/hyprland.conf";`

Use case for this 
people that use stow to manage there dots or nix flake users that sim-link using home manager.

**Comment by nnyyxxxx** [comment]
the path location to hyprlands config file is always going to be in .config, regardless if you symlink it there or not.

Either way it will work with non-symlinked / symlinked, I really don't see a reason in this

**Comment by mrfluffy-dev** [comment]
This is not the case with nix for example yes there will be a file but changing that file will not be possible.
the file will have `.r--r--r--` permissions and even if you where able to change the file the changes would not be persistent across reboots.

and not only that hyprland has a env var for custom config paths making it more inter compatible with native hyprland behavior.

**Comment by nnyyxxxx** [comment]
we originally had a selection menu last month but it was shortly scrapped right after, maybe its time to bring it back ? @adamperkowski :joy:
